export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const ABRIR_ANADIR_CHAT_MODAL = 'ABRIR_ANADIR_CHAT_MODAL';
export const CERRAR_ANADIR_CHAT_MODAL = 'CERRAR_ANADIR_CHAT_MODAL';

export const ANADIR_MENSAJE = 'ANADIR_MENSAJE';
export const COLOCAR_MENSAJES = 'COLOCAR_MENSAJES';

export const OBTENER_CHATS_EXITOSO = 'OBTENER_CHAT_EXITOSO';

